### ISSUE TITLE
Warning: Use Cipheriv for counter mode of aes-256-ctr (M)

### ISSUE THREAD

**Issue by HaroldStruwig** [happner/happn-util-crypto#7]
**TR4127: https://github.com/orgs/FieldServer/projects/218**

getting these warnings when setting `encryptPayloads: true` in happner config:
```
(node:129501) Warning: Use Cipheriv for counter mode of aes-256-ctr
```
see: https://github.com/nodejs/node/issues/16746#issuecomment-341900420

04/01/19-JCE: Closed via https://github.com/happner/happn-3/pull/190/

**Comment by southbite** [comment]
I have just updated and released the latest version of happn-util-crypto (https://github.com/happner/happn-util-crypto) - 0.3.0
this version now included the encrypt with iv feature: https://github.com/happner/happn-util-crypto/blob/master/test/crypto-test.js#L104

We need to do an update to the happn-3 branch you are working on, to use the updated package, and use the symmetricEncryptObjectiv method to encrypt and decrypt encrypted packets after an encryption key has been shared between the happn-3 client and server when encryptPayloads is switched on, here are the tests that validate payload encryption in happn-3:
https://github.com/happner/happn-3/blob/master/test/integration/security/encryptedpayloads_sanity.js

The issue though is that we need to create a new protocol plugin for this, as old clients in the field will be using the previous encryption algorithm to do encryption and decryption. so we need to do the following:

(0) the encryption service needs to expose the symmetricEncryptObjectiv and symmetricDecryptObjectiv methods of the latest happn-util-crypto package https://github.com/happner/happn-3/blob/master/lib/services/crypto/service.js#L12

(1) copy the latest protocol plugin happn-3 (https://github.com/happner/happn-3/blob/master/lib/services/protocol/happn_3.js) to a file happn-4.js in the lib/services/protocol folder

(2) the server generated session secret must now be 32 random characters - this should work for previous protocols, so I think we are ok - here is where the server generates the session secret:
https://github.com/happner/happn-3/blob/master/lib/services/security/service.js#L1184

(3) here is where the server encrypts and decrypts payloads in the protocol file (this would be in your happn-4 protocol plugin):
https://github.com/happner/happn-3/blob/master/lib/services/protocol/happn_3.js#L223
- we need to use the symmetricEncryptObjectiv method instead of the symmetricEncryptObject method to encrypt the payload
- we need to use the session.id  to somehow produce a 16 byte iv (either padded with 0's or trimmed to be 16 characters long)
- we can get the session id here:
https://github.com/happner/happn-3/blob/master/lib/services/protocol/happn_3.js#L265
- we will use the 32 character long secret generated for each session in step (2) as our password

(4) here is where the client decrypts and encrypts payloads:
https://github.com/happner/happn-3/blob/master/lib/client.js#L783
- we need to use the symmetricEncryptObjectiv and symmetricDecryptObjectiv methods now available in the latest latest version of happn-util-crypto to encrypt and decrypt payloads
- encryption and decryption uses the available session properties (id and secret) to create the same iv and secret the server is using for encryption and decryption, by accessing and transforming this.session.secret and this.session.id

(5) the system protocol in package.json needs to be updated to 4, here:
https://github.com/happner/happn-3/blob/master/package.json#L6
- the system version should go up to 8.3.0

(6) we need separate unit and integration tests for all this, so each modified method needs to be tested with mocked variables etc, integration tests go into test/integration/security, unit tests go into test/unit/security

(7) all tests should be passing, and we must also run the browser tests (npm run test-browser) - they test the packet encryption between a headless browser and the server.
